### PR TITLE
fixes #52: strip leading - from exec_stop_pre and exec_stop_post

### LINKED ISSUE #52: exec starting with -
I was looking in my logs and found this

```
Can't exec "-/usr/bin/kdestroy": No such file or directory at /bin/systemctl line 341.
```

### PR DESCRIPTION
**Pull request by muayyad-alsadi**

### CODE REVIEW

**Comment by adelton** [comment]
Merged (partially) as b591a591ed6667f7388f2f6fc4e0d03bbbf0a5ef.

**Comment by muayyad-alsadi** [comment]
is there a reason why not merge the "dnf update -y" part?

**Comment by adelton** [comment]
It is recommended against in https://github.com/projectatomic/container-best-practices/blob/master/creating/creating_index.adoc:

Avoid updating software supplied by base-image unless necessary. Base images themselves are meant to be updated on a regular basis by the supplier and provide software that has been tested for a particular environment. Also, updating base-image software in layered images can introduce unexpected problems or bring in unwanted dependencies and in certain cases significantly expand the image size.

**Comment by muayyad-alsadi** [comment]
thank you.

**Pull request closed without merging**
